### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries Used Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size = 10000

#### One Hot Representation

In [6]:
onehot_repr = [one_hot(words,voc_size)for words in sent] 

In [7]:
print(onehot_repr)

[[6014, 2750, 8997, 9732], [6014, 2750, 8997, 8803], [6014, 651, 8997, 2709], [9674, 4579, 3896, 2507, 3158], [9674, 4579, 3896, 2507, 3812], [400, 6014, 780, 8997, 2688], [6392, 443, 4268, 2507]]


### Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 8

In [11]:
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)

In [12]:
print(embedded_docs)

[[   0    0    0    0 6014 2750 8997 9732]
 [   0    0    0    0 6014 2750 8997 8803]
 [   0    0    0    0 6014  651 8997 2709]
 [   0    0    0 9674 4579 3896 2507 3158]
 [   0    0    0 9674 4579 3896 2507 3812]
 [   0    0    0  400 6014  780 8997 2688]
 [   0    0    0    0 6392  443 4268 2507]]


In [13]:
dim = 10

In [14]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
print(model.predict(embedded_docs))

[[[-0.04897623  0.0459562  -0.01338699  0.01862912  0.03082787
    0.00967795  0.01760732  0.01485764  0.00600898 -0.00159769]
  [-0.04897623  0.0459562  -0.01338699  0.01862912  0.03082787
    0.00967795  0.01760732  0.01485764  0.00600898 -0.00159769]
  [-0.04897623  0.0459562  -0.01338699  0.01862912  0.03082787
    0.00967795  0.01760732  0.01485764  0.00600898 -0.00159769]
  [-0.04897623  0.0459562  -0.01338699  0.01862912  0.03082787
    0.00967795  0.01760732  0.01485764  0.00600898 -0.00159769]
  [ 0.00621575 -0.00972648  0.00139682  0.03080025 -0.0186721
   -0.03734612 -0.01726704  0.0015008  -0.00131416  0.04352235]
  [-0.04986468  0.0409724  -0.02650743 -0.00623538 -0.0096068
    0.04797274  0.01432849  0.04792556  0.03372702  0.02789349]
  [ 0.03884954  0.03743282 -0.02428173 -0.01040983 -0.00137025
    0.02786672  0.00612056 -0.02135151 -0.0314719   0.0214893 ]
  [-0.04722955 -0.0352251   0.03472561  0.00054513  0.02418684
   -0.03458368 -0.02774044  0.03637178  0.02963245

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 6014, 2750, 8997, 9732])

In [18]:
print(model.predict(embedded_docs)[0])

[[-0.04897623  0.0459562  -0.01338699  0.01862912  0.03082787  0.00967795
   0.01760732  0.01485764  0.00600898 -0.00159769]
 [-0.04897623  0.0459562  -0.01338699  0.01862912  0.03082787  0.00967795
   0.01760732  0.01485764  0.00600898 -0.00159769]
 [-0.04897623  0.0459562  -0.01338699  0.01862912  0.03082787  0.00967795
   0.01760732  0.01485764  0.00600898 -0.00159769]
 [-0.04897623  0.0459562  -0.01338699  0.01862912  0.03082787  0.00967795
   0.01760732  0.01485764  0.00600898 -0.00159769]
 [ 0.00621575 -0.00972648  0.00139682  0.03080025 -0.0186721  -0.03734612
  -0.01726704  0.0015008  -0.00131416  0.04352235]
 [-0.04986468  0.0409724  -0.02650743 -0.00623538 -0.0096068   0.04797274
   0.01432849  0.04792556  0.03372702  0.02789349]
 [ 0.03884954  0.03743282 -0.02428173 -0.01040983 -0.00137025  0.02786672
   0.00612056 -0.02135151 -0.0314719   0.0214893 ]
 [-0.04722955 -0.0352251   0.03472561  0.00054513  0.02418684 -0.03458368
  -0.02774044  0.03637178  0.02963245 -0.04977727]]